SCREEN_WIDTH, SCREEN_HEIGHT = 800, 600
GAME_NAME = 'PGJ Hw 2022'
FPS = 60

TILE_SIZE = 62

WALL_KEY = 'GROUND'
NORMAL_KEY = 'NORMAL'
ITEM_KEY = 'ITEM'
STATION_KEY = 'STATION'
DOOR_KEY = 'DOOR'
EXIT_KEY = 'EXIT'
PLAYER_KEY = 'PLAYER'
MONEMY_KEY = 'MONEMY'
JUMPSCARE_KEY = 'JUMPSCARE'
TEXT_KEY = 'TEXT'

IDLE = 'IDLE'
WALK_RIGHT = 'WALK_RIGHT'
WALK_LEFT = 'WALK_LEFT'
WALK_UP = 'WALK_UP'
WALK_DOWN = 'WALK_DOWN'
